services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_pass
      POSTGRES_DB: todo_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    # Evitar problemas de credenciales
    pull_policy: missing

  backend:
    build:
      context: ./backend
      pull: false # No intentar pull de imágenes base
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgresql://todo_user:todo_pass@db:5432/todo_db
      - DOCKER_BUILDKIT=0 # Desactivar BuildKit si causa problemas
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend/my-app
      pull: false # No intentar pull de imágenes base
    volumes:
      - ./frontend/my-app:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - FAST_REFRESH=true
      - DOCKER_BUILDKIT=0
    depends_on:
      - backend

volumes:
  db_data:
